name: Update DTI Website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [repo-push]
  push:
    branches:
      - master

jobs:
  update_website:
    name: Updating website
    runs-on: ubuntu-latest
    steps:
      - name: Clone dtiwebsite_generator
        uses: actions/checkout@v4
        with:
          path: dtiwebsite_generator

      - name: Clone group-data
        uses: actions/checkout@v4
        with:
          repository: KasukabeDefenceForce/group-data
          path: group-data
          token: ${{ secrets.SITE_TEST}}

      - name: Clone deepthought-initiative.github.io
        uses: actions/checkout@v4
        with:
          repository: KasukabeDefenceForce/deepthought-initiative.github.io
          path: deepthought-initiative.github.io
          token: ${{ secrets.SITE_TEST }}

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Update pip and install Jupyter and Pandas
        run: |
          pip install --upgrade pip jupyter pandas

      - name: Clear and setup directories inside deepthought-initiative.github.io
        run: |
          ./notebooks/setup.sh
        working-directory: dtiwebsite_generator

      - name: Run Notebooks
        run: |
          jupyter nbconvert --to python create_htmls.ipynb
          python3 create_htmls.py
        working-directory: dtiwebsite_generator/notebooks

      - name: Push Website
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit --allow-empty -m "Push from website generator"
          git push
        working-directory: deepthought-initiative.github.io
